### ISSUE TITLE
gauge metrics from cache plugin are incorrect when multiple servers use cache plugin

### ISSUE THREAD

**Issue by elijahandrews** [miekg/coredns#5123] opened 2022-01-25 20:21 UTC
**What happened**:

Currently, cache metrics are not tagged by zone; if you have multiple server blocks with the cache plugin enabled, the metrics for the different servers compete for last write (for gauges) or combine (for counters).

**What you expected to happen**:

When multiple server blocks use the cache plugin, I expect metrics emitted by the cache plugin to be correct and labeled by zone.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce this issue, consider the following Corefile:

```
(defaults) {
    prometheus 0.0.0.0:9253
    forward . /etc/resolv.conf
    cache
}

datadoghq.com cluster.local {
    import defaults
}

. {
    import defaults
}
```

After starting CoreDNS 1.8.6, make a few DNS queries to the three zones:

```
$ dig @127.0.0.1 +short datadoghq.com google.com doesnotexist.cluster.local
99.84.42.100
99.84.42.61
99.84.42.44
99.84.42.47
142.251.41.14

```

We can then curl the Prometheus endpoint for metrics emitted by the cache plugin:

```
$ curl -s localhost:9253/metrics | grep "^coredns_cache"
coredns_cache_entries{server="dns://:53",type="denial"} 1
coredns_cache_entries{server="dns://:53",type="success"} 1
coredns_cache_misses_total{server="dns://:53"} 3
coredns_cache_requests_total{server="dns://:53"} 3
```

For the counter metrics (`coredns_cache_misses_total` and `coredns_cache_requests_total`), the values are correct, but we cannot identify the values for the individual caches.

For the gauge metric (`coredns_cache_entries`), the values are incorrect, since the last write to the gauge wins. The sum of the denial and success cache should be 3, but reads 2. 

**Environment**:

- the version of CoreDNS: 1.8.6
- OS (e.g: `cat /etc/os-release`): output above is from OS X 10.15.7 running on x64

**Comment by chrisohaver** [comment] 2022-01-26 16:53
This issue describes a bug and an enhancement.
The gauge write competition is definitely a bug.
The counter merging is not a bug, since the values are accurate in total. This is an enhancement.

At the very least we should fix the gauge write competition problem.
Adding zones as a new vector (as in #5124) will increase the amount of metric data produced.
If we are keen to not add a new vector to cache metrics, I think it could be fixed with global atomic counters per server.

**Comment by atollena** [comment] 2022-01-31 10:36
> If we are keen to not add a new vector to cache metrics, I think it could be fixed with global atomic counters per server.

What is your sentiment on this? Do you have any rule of thumb or guidelines on when it is worth the trade-off to increase the number of metrics? There is a cost to adding a zone label, but without this information it is quite difficult to size the caches correctly.

**Comment by chrisohaver** [comment] 2022-01-31 16:27
> What is your sentiment on this?

I lean toward adding the zones as vectors for at least the one cache size gauge metric (which is currently broken).  
Although `zones` is a potentially very long string for a vector, it is used in other metrics.
The opinions of _cache_ plugin CODEOWNERs carry more weight than mine here.

> Do you have any rule of thumb or guidelines

Not that I am aware of.

**Closed as completed** 2022-02-14 17:10 UTC
Labels: bug, enhancement, plugin/cache
