### ISSUE TITLE
kubernetes coredns is in CrashLoopBackOff status when the /etc/resolv.conf is empty

### ISSUE THREAD

**Issue by yankay** [miekg/coredns#5764] opened 2022-11-18 06:34 UTC
**What happened**:

kubernetes coredns is in CrashLoopBackOff status with "no nameservers found" error.
And the /etc/resolv.conf is emtry. However, currently I don't use any external dns at all.

The same issue is at:

- https://serverfault.com/questions/1081685/kubernetes-coredns-is-in-crashloopbackoff-status-with-no-nameservers-found-err
- https://discuss.kubernetes.io/t/coredns-is-in-crashloopbackoff-state-with-no-nameservers-found-error-log/17863
- https://github.com/kubean-io/kubean/issues/178
- https://github.com/kubernetes-sigs/kubespray/issues/9497

**What you expected to happen**:

If  the `/etc/resolv.conf` is emtry. The coredns not crash.

**How to reproduce it (as minimally and precisely as possible)**:

Install Kubernetes on the machine with `/etc/resolv.conf`  not setting.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:

v1.8.6
 
- Corefile:

```
forward . /etc/resolv.conf {
          prefer_udp
          max_concurrent 1000
        }
```

- logs, if applicable:
```
`plugin/forward: no nameservers found`
```

- OS (e.g: `cat /etc/os-release`):

```
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
```
- Others:

**Comment by chrisohaver** [comment] 2022-11-18 14:07
Remove the forward plugin from your corefile.

**Comment by chrisohaver** [comment] 2022-11-18 14:54
This is expected behavior, since configuring _forward_ without upstreams is an invalid configuration. Exiting at start up is the expected behavior when a plugin encounters an invalid configuration.  Despite the name of the K8s pod status, CoreDNS is not "crashing".

The proper fix for this is to not use the _forward_ plugin if you do not need to forward anything upstream.
Kubernetes installers should ask at install time if forwarding is desired and include/exclude the _forward_ plugin as needed. When including it, the installer should check the configured resolv.conf file and error if it contains no servers.

As an _enhancement_, we could consider altering the _forward_ plugin to issue a warning and "disable itself" if it finds there are no upstreams configured.  However AFAIK no other plugins intentionally act this way if they are misconfigured, so I'd be hesitant to introduce this kind of expectation.

**Comment by yankay** [comment] 2022-11-21 02:33
> This is expected behavior, since configuring _forward_ without upstreams is an invalid configuration. Exiting at start up is the expected behavior when a plugin encounters an invalid configuration. Despite the name of the K8s pod status, CoreDNS is not "crashing".
> 
> The proper fix for this is to not use the _forward_ plugin if you do not need to forward anything upstream. Kubernetes installers should ask at install time if forwarding is desired and include/exclude the _forward_ plugin as needed. When including it, the installer should check the configured resolv.conf file and error if it contains no servers.
> 
> As an _enhancement_, we could consider altering the _forward_ plugin to issue a warning and "disable itself" if it finds there are no upstreams configured. However AFAIK no other plugins intentionally act this way if they are misconfigured, so I'd be hesitant to introduce this kind of expectation.

Thanks @chrisohaver for your advise.
I have added a check to the 'KubeSpray' Installer, ref https://github.com/kubernetes-sigs/kubespray/pull/9502 .

**Closed as completed** 2022-11-23 17:04 UTC

**Comment by chrisohaver** [comment] 2022-11-25 23:38
@yankay please note when removing the _forward_ plugin, you should also remove the `fallthrough` line since there is nothing to fallthrough to anymore.

**Comment by chrisohaver** [comment] 2022-11-26 01:02
@yankay, and also the _loop_ plugin

**Comment by yankay** [comment] 2022-11-29 01:56
> @yankay, and also the _loop_ plugin

Thank you very much
