### ISSUE TITLE
Wrong platforms set on Docker images since 1.9.0

### ISSUE THREAD

**Issue by der-eismann** [miekg/coredns#5509] opened 2022-07-12 16:18 UTC
Not sure what you changed in your CI/release process since 1.9.0, but somehow all container images for one specific version have the `linux/amd64` platform set instead of `linux/arm64` or other platforms:
![screenshot-20220712-180856](https://user-images.githubusercontent.com/10406217/178541202-a005be99-3a1d-4e21-9ad1-b660473b70fc.png)

Maybe you can verify if this is a problem on the Docker Hub side or actually the images that you are building. I can pull images for `linux/arm64` by using `podman pull --platform linux/arm64 coredns/coredns:1.9.3` successfully, so maybe it's just a labeling error?

```
$ podman pull --platform linux/arm64 coredns/coredns:1.9.3
$ podman image inspect coredns/coredns:1.9.3
...
          "RepoDigests": [
               "docker.io/coredns/coredns@sha256:85c4677668f548da72cc0194663ae9d412cac8f239551ca90c0941c9c1ad8685",
               "docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a"
          ],
...
          "Architecture": "amd64",
          "Os": "linux",
...
$ podman system prune -a -f
$ podman pull --platform linux/amd64 coredns/coredns:1.9.3
$ podman image inspect coredns/coredns:1.9.3
...
          "RepoDigests": [
               "docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a",
               "docker.io/coredns/coredns@sha256:bdb36ee882c13135669cfc2bb91c808a33926ad1a411fee07bd2dc344bb8f782"
          ],
...
          "Architecture": "amd64",
          "Os": "linux",
...
```

**Comment by chrisohaver** [comment] 2022-07-12 16:25
duplicate of #5363

**Closed as completed** 2022-07-12 16:26 UTC
Labels: bug
