### ISSUE TITLE
when lameduck and config-reload are enabled, editing the config causes all pods in the deployment to go unready

### ISSUE THREAD

**Issue by connorworkman** [miekg/coredns#5471] opened 2022-06-27 21:19 UTC
I'm submitting this as a question instead of a bug since it might be the intended behavior but it seems undesirable.
Is this the expected behavior? Any advice on how to avoid a total service outage when updating the configmap?

**What happened**:
Editing the coredns configmap, when lameduck is enabled, causes all pods in the deployment to go unready during config reload.

**What you expected to happen**:
Config reload should occur without entering lameduck mode if possible, as there's no guarantee that pods will reload config one at a time.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a coredns deployment with lameduck mode and readiness/liveness probes.
Edit the configmap (i.e. change lameduck duration from 21s to 22s) and wait for config reload to trigger.
Observe that pods fail readiness probe until lameduck mode ends, causing total service outage.

**Environment**:

- the version of CoreDNS: 1.8.7
- Corefile:
```
    .:53 {
        log . {
          class denial
          class error
        }
        errors
        health {
          lameduck 22s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

- logs, if applicable:
```
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 21s
...
[INFO] plugin/reload: Running configuration MD5 = 2f64ae2f830ad4fa527721f112bb527f
[INFO] Reloading complete
```

- OS (e.g: `cat /etc/os-release`):
Amazon Linux 2 Karoo

- Probe configuration:
```
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```

**Comment by chrisohaver** [comment] 2022-06-27 22:13
Hmm, It kind of sounds like lameduck is triggering on a reload.  It shouldn't be doing that.

**Comment by chrisohaver** [comment] 2022-06-27 22:21
Looks like it was introduced by https://github.com/coredns/coredns/pull/2812.

**Comment by chrisohaver** [comment] 2022-06-27 23:10
> Looks like it was introduced by #2812.

Actually - it looks like it has been that way since lameduck was introduced.

**Comment by chrisohaver** [comment] 2022-06-27 23:37
May have been introduced with https://github.com/coredns/coredns/pull/4167.

I think there are two ways to "fix" this:
1. don't go into lameduck when reloading (what #5472 proposes)
2. don't report unready when reloading (which may have been introduced by #4167).

Perhaps both should be fixed, although for the 2nd, reloading doesn't normally take long enough for this to cause an issue (if we don't lameduck during reloads).

**Comment by chrisohaver** [comment] 2022-06-28 00:19
> 2. don't report unready when reloading (which may have been introduced by https://github.com/coredns/coredns/pull/4167).

Actually I don't think that's a good fix.  And that PR would not have introduced it anyways - the _ready_ listener is closed on reload, so being unready on reload was expected behavior prior to #4167 (#4167 fixes an issue related to persistent connections).

The "unready during lameduck" behavior is due to _ready_ coming before _health_ in plugin.cfg.  If that were reversed, the lameduck sleep (in health) would occur before _ready_ closes its listener.  But swapping the order would also cause coredns to report ready during a shut down, which we do not want.

**Closed as completed** 2022-07-06 17:52 UTC
Labels: bug, question
